### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [adservicecom/gtm_adservice_conversion#1]
Thank you for submitting template to the gallery. However, there are a few issues that needs to be resolved ahead of approving the template for the gallery.

1. The sendPixel should have both onSuccess and onFailure. Please refer to [https://developers.google.com/tag-manager/templates/api#sendpixel](https://developers.google.com/tag-manager/templates/api#sendpixel)
2. Please use [encodeUriComponent](https://developers.google.com/tag-manager/templates/api#encodeuri) when referencing user input in URLs.

**Comment by adservicecom** [comment]
Hi,

Thank you for your feedback.
1. Are you sure that this is necessary ? 
Its not part of the example code: https://developers.google.com/tag-manager/templates/permissions#send_pixel
and it seems unnecessary to add these functions if there is no specific functions to be called in case of success or failure. The point is just to call the pixel.
2. I have corrected this in the newest update.

**Comment by adservicecom** [comment]
> Thank you for submitting template to the gallery. However, there are a few issues that needs to be resolved ahead of approving the template for the gallery.
> 
>     1. The sendPixel should have both onSuccess and onFailure. Please refer to https://developers.google.com/tag-manager/templates/api#sendpixel
> 
>     2. Please use [encodeUriComponent](https://developers.google.com/tag-manager/templates/api#encodeuri) when referencing user input in URLs.



> Thank you for submitting template to the gallery. However, there are a few issues that needs to be resolved ahead of approving the template for the gallery.
> 
>     1. The sendPixel should have both onSuccess and onFailure. Please refer to https://developers.google.com/tag-manager/templates/api#sendpixel
> 
>     2. Please use [encodeUriComponent](https://developers.google.com/tag-manager/templates/api#encodeuri) when referencing user input in URLs.

@praveena-pappu we updated the template, when can we expect the review to continue?
